### ISSUE TITLE
instantiate Guard class Target [Illuminate\Contracts\Auth\UserProvider] is not instantiable

### ISSUE THREAD

**Issue by toinkiie** [Kbwebs/MultiAuth#1]
Target [Illuminate\Contracts\Auth\UserProvider] is not instantiable

in Guard class.

**Comment by kasperbasse** [comment]
Hi,
In what scenario is it the problem are coming, for i can't get the same problem with me. ? :)

**Comment by mundiir** [comment]
When I use standard Laravel middleware "guest" in AuthController I get "Class auth.driver does not exist".
How to use your Guard as standard Laravel Guard Contract?

**Comment by kasperbasse** [comment]
Hi @mundiir 
I have now updated this file: MultiAuth/src/AuthServiceProvider.php
I have now added support for auth.driver, so it should work correctly now, if the error still continues please contact me again :)

**Comment by thomasdola** [comment]
Interface 'App\AuthenticatableContract' not found

when trying to register a new user.

public function registerUser(Request $request)
	{
		$this->validate($request,
			[
				'name'=>'required|unique:users',
				'email'=>'required|unique:users|email',
				'password'=>'required',
				'agree' =>'required'
			]);

		User::create($request->all());

		if(Auth::user()->login($user))
		{
			return redirect()->intended('/my-profile', true);
		}
	}

**Comment by kasperbasse** [comment]
Hi @thomasdola 
Where do you get this error. ?
You can try the update with the new release: v1.0, and see if the error is not going away. :)

**Comment by kasperbasse** [comment]
Hi @thomasdola 
I am closing this issue now, if you still have problems, you can open a new issue :)
