### ISSUE TITLE
Undefined index: password

### ISSUE THREAD

**Issue by Rizal-Afani** [Kbwebs/MultiAuth#13]
Hi Sir, I use this package but i get an error when i submiting form..

ErrorException in EloquentUserProvider.php line 112:
Undefined index: password

**Comment by Rizal-Afani** [comment]
Oh it Solved. Just Replace trait AuthenticatesUsers line 50 : 
if (Auth::attempt($credentials, $request->has('remember'))) 
Replace With
 if (Auth::user()->attempt($credentials, $request->has('remember')))

**Comment by kasperbasse** [comment]
Hi @Rizal-Afani 
Thats good that you found a solution, i will close the issue now :)
