### ISSUE TITLE
How to access model in implementation

### ISSUE THREAD

**Issue by toinkiie** [Kbwebs/MultiAuth#2]
Like this : Accessing The Logged In User

Once a user is authenticated, you may access the User model / record:

$email = Auth::user()->email;

**Comment by kasperbasse** [comment]
Hi,
To access the authenticated user model, you can do it like this:
Auth::user()->get()
Or if you only want to get the email:
Auth::user()->get()->email
I have just now updated the README for this. 
I hope it helps on your problem :)
