### ISSUE TITLE
BindingResolutionException in Container.php line 744:

### ISSUE THREAD

**Issue by sourabh13** [Kbwebs/MultiAuth#4]
Target [Illuminate\Contracts\Auth\Registrar] is not instantiable.

**Comment by kasperbasse** [comment]
Hi @sourabh13 
I know it is long time ago you postede this issue, but where do you get this error, if it still present to you. ? :)

**Comment by sourabh13** [comment]
Hello, 
First of all thnx for the multiauth package, it was a great help to me and actually I got past that issue. It was an error at my end .. :). Sorry forgot to close this issue.
