### ISSUE TITLE
Release and tags

### ISSUE THREAD

**Issue by vinicius73** [Kbwebs/MultiAuth#5]
Working with dev-master is complicated and dangerous.
@kasperbasse  You can create a tag or release? Even a pre-release helps a lot.

**Comment by vluzrmos** [comment]
:+1:

**Comment by marcellorg** [comment]
:+1:

**Comment by vinicius73** [comment]
@kasperbasse ?

**Comment by kasperbasse** [comment]
Hello, i will try to take a look at that, i am not strongest in git yet.  ;)
But thank you for the tip @vinicius73. :)

**Comment by kasperbasse** [comment]
Hi @vinicius73 
I have now created a new release with version number:
"kbwebs/multiauth": "~1.0", is it like you want it to be :)

**Comment by vinicius73** [comment]
thanks!
