### ISSUE TITLE
Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable.

### ISSUE THREAD

**Issue by rajanrawal** [Kbwebs/MultiAuth#8]
Laravel 5.1.16

php artisan clear compiled

composer updated 

composer dump-autoload -o

All tried but getting

App crashing. Throwing error:
```
BindingResolutionException in Container.php line 744: 
Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable.
```

**Comment by kasperbasse** [comment]
Hi @rajanrawal.
I have now updatede the package with a new version:
"kbwebs/multiauth": "~1.0"
Please try that, and report back to me, if any errors. :)
