### ISSUE TITLE
Authenticate Middleware

### ISSUE THREAD

**Issue by Schnapse** [Kbwebs/MultiAuth#9]
Good evening,

First of all, congratulations for your package, easy to use and working as expected. However, I've just a question concerning the implementation of the Guard in middlewares. I kept the originals Authenticate and RedirectIfAuthenticated middlewares.

```php
    public function handle($request, Closure $next)
    {
        if($this->auth->guest())
        {
            if($request->ajax())
            {
                return response('Unauthorized.', 401);
            }
            else
            {
                return redirect()->guest('...');
            }
        }

        return $next($request);
    }
```

Unfortunately, the guest() function isn't able to make the difference between user/admin side. To make it working, I create two different middlewares for each side and I force the test like this :

```php
    public function handle($request, Closure $next)
    {
        if(!Auth::admin()->get())
        {
            if($request->ajax())
            {
                return response('Unauthorized.', 401);
            }
            else
            {
                return redirect()->guest('...');
            }
        }

        return $next($request);
    }
```

I'm sure it's not the right way to do it but it's working as I expected. It's quietly the same in the RedirectIfAuthenticated middleware with the check function. Do you have some advice for the best use of your package ?

Thanks in advance.

**Comment by kasperbasse** [comment]
Hi @Schnapse 
A quick solution and more correct will be:
``Auth::user()->check()`` 
``Auth::user()->guest()``
Just change user() with the user you want to check on. 
What do you think about that. :)
Tip: Maybe you can have some check in that middleware and perhaps send a parameter with it from route or so. :)

**Comment by Schnapse** [comment]
Thanks @kasperbasse, it's working fine !
